### ISSUE TITLE
Browse page 'Limit your search' dropdowns display incorrectly.

### ISSUE THREAD

**Issue by younga3** [UW-Libraries/druw#11]
Dropdowns for 'Type', 'Creator', and 'Keyword' display with only one? pixel width.

**Comment by younga3** [comment]
Isolated problem to app/assets/stylesheets/local_rules.scss

**Comment by younga3** [comment]
Removing 'Page Structure' section fixes it for now.

**Comment by younga3** [comment]
Removing 'Page Structure' section fixes it for now.

**Comment by younga3** [comment]
Removing 'Page Structure' section fixes it for now.

**Comment by dtolmie** [comment]
Yeah.  The flex box entry does not exist in current community code. It will be interesting to see what the repercussions are site-wide of simply removing that.

**Comment by dtolmie** [comment]
Yeah.  The flex box entry does not exist in current community code. It will be interesting to see what the repercussions are site-wide of simply removing that.

**Comment by dtolmie** [comment]
Yeah.  The flex box entry does not exist in current community code. It will be interesting to see what the repercussions are site-wide of simply removing that.

**Comment by younga3** [comment]
Removing the following section.
`/* ------------------------ */ 
/* ---- Page Structure ---- */ 
/* ------------------------ */ 
 
/* make the footer sticky */ 
html { 
   height: 100%; 
} 
body { 
   height: 100vh; 
   display: flex; 
   flex-direction: column; 
   margin-bottom: 0; /* unsets Sufia's attempt to make a sticky footer */ 
} 
main#content { 
   flex: 1 0 auto; 
} 
footer#page-footer { 
   flex-shrink: 0; 
}
`

**Comment by younga3** [comment]
Fixed with PR #12

**Comment by dtolmie** [comment]
🎉
